"""init

Revision ID: 26707067c61e
Revises: 7f08694bed2f
Create Date: 2018-12-31 12:08:27.409608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26707067c61e'
down_revision = '7f08694bed2f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_brand_name'), 'brand', ['name'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_brand_name'), 'brand', type_='unique')
    # ### end Alembic commands ###
